version: '3'
services:

  inventory-management:
    image: inventory-management
    build: 
      context: ./inventory-management
      dockerfile: Dockerfile
    container_name: inventory-management
    ports:
     - "4000:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://db_223306781sit722week9_user:0IzW1J8P8ubeNXYrYQr5Witl0iX3YTyn@dpg-crcp3mrv2p9s73ck84ng-a.oregon-postgres.render.com/db_223306781sit722week9
    restart: "no"

  book-catalog:
    image: book-catalog
    build: 
      context: ./book-catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    ports:
     - "4001:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://db_223306781sit722week9_user:0IzW1J8P8ubeNXYrYQr5Witl0iX3YTyn@dpg-crcp3mrv2p9s73ck84ng-a.oregon-postgres.render.com/db_223306781sit722week9
    restart: "no"