set -u # or set -o nounset
: "$CONTAINER_REGISTRY"
: "$VERSION"
: "$APPLICATION_NAME"
echo "$CONTAINER_REGISTRY/$APPLICATION_NAME:$VERSION --file ./$APPLICATION_NAME/Dockerfile"
docker build -t $CONTAINER_REGISTRY/$APPLICATION_NAME:$VERSION --file ./$APPLICATION_NAME/Dockerfile