# 
# GitHub Actions workflow.
#
# Automatically deploys the Node.js microservice to Kubernetes on push to any branch. 
# For real use you might want to restrict this to the "prod" branch.
#

name: Deploy Microservices

on:
  #
  # Deploys the microservice on push to the main branch of this code repository.
  #
  push: 
    branches:
      - main

  #
  # Allows deployment to be invoked manually through the GitHub Actions user interface.
  #
  workflow_dispatch: 

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    env:
      VERSION: ${{ github.sha }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      AZURE_APP_NAME: ${{ secrets.AZURE_APP_NAME }}
      REGISTRY_UN: ${{ secrets.AZURE_APP_NAME }}
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      AZURE_RESOURCE_GROUP_NAME: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}

    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3

       # login to Azure services
      - name: Azure login
        run: az login --service-principal -t ${{ secrets.AZURE_TENANT_ID }} -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CREDENTIALS }}
      
      # Get container registry URL --output
      - name: Azure CLI container registry URL
        id: CONTAINER_REGISTRY
        run: |
          h=$(az acr list -g $AZURE_RESOURCE_GROUP_NAME --query "[].{acrLoginServer:loginServer}[0].acrLoginServer" --output tsv) 

          echo "::set-output name=h::$h"

      # Get container registry password --output
      - name: Azure CLI container registry password
        id: REGISTRY_PW
        run: |
          h=$(az acr credential show -n ${{ steps.CONTAINER_REGISTRY.outputs.h }} --query 'passwords[0].value' --output tsv) 

          echo "::set-output name=h::$h"   

      # Get kubernetes credentials --output
      - name: Azure CLI Kubernetes Credentials
        run: az aks get-credentials --resource-group $AZURE_RESOURCE_GROUP_NAME --name $AZURE_APP_NAME

      - name: Set KUBE_CONFIG env
        run: | 
              cat ~/.kube/config | base64 --decode > config.txt

      - name: export KUBECONFIG path
        run: echo "KUBE_CONFIG=config.txt" >> $GITHUB_ENV

      #- name: Set KUBE_CONFIG env
      #  run: | 
      #        cat ~/.kube/config | base64 > ~/kubeconfig.txt
      #        echo "$KUBE_CONFIG" > ~/kubeconfig.txt

      #- name: Azure CLI container registry password
      #  id: KUBE_CONFIG
      #  run: |
      #    h=$(cat ~/.kube/config | base64) 

      #    echo "::set-output name=h::$h"   

      #
      # Installs Kubectl and connects it to the cluster.
      #
      # https://github.com/marketplace/actions/kubernetes-cli-kubectl
      #
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config:  $KUBE_CONFIG
          kubectl-version: v1.30.3

      #
      # Builds the Docker images.
      #
      - name: Build book-catalog 
        env:
          NAME: book-catalog
          DIRECTORY: book-catalog
          CONTAINER_REGISTRY: ${{ steps.CONTAINER_REGISTRY.outputs.h }}
        run: | 
               chmod +x ./scripts/build-image.sh
               ./scripts/build-image.sh
      
      - name: Build inventory-management
        env:
          NAME: inventory-management
          DIRECTORY: inventory-management
          CONTAINER_REGISTRY: ${{ steps.CONTAINER_REGISTRY.outputs.h }}
        run: | 
               chmod +x ./scripts/build-image.sh
               ./scripts/build-image.sh

      #
      # Publishes the Docker images to the container registry.
      #
      - name: Publish book-catalog 
        env:
          NAME: book-catalog
          DIRECTORY: book-catalog
          CONTAINER_REGISTRY: ${{ steps.CONTAINER_REGISTRY.outputs.h }}
          REGISTRY_PW: ${{ steps.REGISTRY_PW.outputs.h }}
        run: | 
               chmod +x ./scripts/push-image.sh
               ./scripts/push-image.sh

      - name: Publish inventory-management
        env:
          NAME: inventory-management
          DIRECTORY: inventory-management
          CONTAINER_REGISTRY: ${{ steps.CONTAINER_REGISTRY.outputs.h }}
          REGISTRY_PW: ${{ steps.REGISTRY_PW.outputs.h }}
        run: | 
               chmod +x ./scripts/push-image.sh
               ./scripts/push-image.sh
      #
      # Expands the configuration template and deploys the microservice.
      #
      - name: Deploy
        env:
          CONTAINER_REGISTRY: ${{ steps.CONTAINER_REGISTRY.outputs.h }}
        run: | 
               chmod +x ./scripts/deploy.sh
               ./scripts/deploy.sh
      
      - name: Sleep for 20 seconds
        run: sleep 20s
        shell: bash

      #
      # Getting external IP address for accessing deployment.
      #
      - name: 'Getting Deployment address'
        run: 'kubectl get services'